---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - samplevolumne.operator.yogeshsharma.me
  resources:
  - samplevolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - samplevolumne.operator.yogeshsharma.me
  resources:
  - samplevolumes/finalizers
  verbs:
  - update
- apiGroups:
  - samplevolumne.operator.yogeshsharma.me
  resources:
  - samplevolumes/status
  verbs:
  - get
  - patch
  - update
