# permissions for end users to edit samplevolumes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: samplevolume-editor-role
rules:
- apiGroups:
  - samplevolumne.operator.yogeshsharma.me
  resources:
  - samplevolumes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - samplevolumne.operator.yogeshsharma.me
  resources:
  - samplevolumes/status
  verbs:
  - get
